#!/bin/sh


cp test.ico apple-touch-icon-114x114.png
cp test.ico apple-touch-icon-120x120.png
cp test.ico apple-touch-icon-144x144.png
cp test.ico apple-touch-icon-152x152.png
cp test.ico apple-touch-icon-57x57.png
cp test.ico apple-touch-icon-60x60.png
cp test.ico apple-touch-icon-72x72.png
cp test.ico apple-touch-icon-76x76.png
cp test.ico apple-touch-icon.png
cp test.ico apple-touch-icon-precomposed.png
cp test.ico favicon-160x160.png.png
cp test.ico favicon-16x16.png
cp test.ico favicon-196x196.png
cp test.ico favicon-32x32.png
cp test.ico favicon-96x96.png
cp test.ico favicon.ico
cp test.ico mstile-144x144.png
cp test.ico mstile-150x150.png
cp test.ico mstile-310x150.png
cp test.ico mstile-310x310.png
cp test.ico mstile-70x70.png
