<!-- GitHub Star -->
<a class="github-button" href="https://github.com/zephyrproject-rtos/zephyr" data-count-href="/zephyrproject-rtos/zephyr/stargazers" data-count-api="/repos/zephyrproject-rtos/zephyr#stargazers_count" data-count-aria-label="# stargazers on GitHub" aria-label="Star zephyrproject-rtos/zephyr on GitHub">Star</a>
<!-- GitHub fork -->
<a class="github-button" href="https://github.com/zephyrproject-rtos/zephyr/fork" data-count-href="/zephyrproject-rtos/zephyr/network" data-count-api="/repos/zephyrproject-rtos/zephyr#forks_count" data-count-aria-label="# forks on GitHub" aria-label="Fork zephyrproject/zephyr on GitHub">Fork</a>
<script>
window.twttr=(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],t=window.twttr||{};if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);t._e=[];t.ready=function(f){t._e.push(f);};return t;}(document,"script","twitter-wjs"));
</script>
